Controllers/LeaveAllocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using leave_management.Contracts;
using leave_management.Data;
using leave_management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace leave_management.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LeaveAllocationController : Controller
    {

        //private readonly ILeaveTypeRepository _leaverepo;
        //private readonly ILeaveAllocationRepository _leaveallocationrepo;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<Employee> _userManager;

        public LeaveAllocationController(
            ILeaveTypeRepository leaverepo,
            ILeaveAllocationRepository leaveallocationrepo,
            IUnitOfWork unitOfWork,
            IMapper mapper,
            UserManager<Employee> userManager
        )
        {
            //_leaverepo = leaverepo;
            //_leaveallocationrepo = leaveallocationrepo;
            _unitOfWork = unitOfWork; 
            _mapper = mapper;
            _userManager = userManager;
        }

        public async Task< IActionResult> Index()
        {
            //var leavetypes = await _leaverepo.FindAll();
            var leavetypes = await _unitOfWork.LeaveTypes.FindAll();
            var mappedLeaveTypes = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leavetypes.ToList());
            var model = new CreateLeaveAllocationVM
            {
                LeaveTypes = mappedLeaveTypes,
                NumberUpdated = 0
            };
            return View(model);
        }

        public async Task< ActionResult> SetLeave(int id)
        {
            //var leavetype = await _leaverepo.FindById(id);
            var leavetype = await _unitOfWork.LeaveTypes.Find(q => q.Id == id);
            var employees = await _userManager.GetUsersInRoleAsync("Employee");
            var period = DateTime.Now.Year; 
            foreach (var emp in employees)
            {
                // var checkAllocation =await _leaveallocationrepo.CheckAllocation(id, emp.Id);

                if (await _unitOfWork.LeaveAllocations.IsPresent(q => q.EmployeeId == emp.Id
                            && q.LeaveTypeId == id
                            && q.Period == period))
                    continue;
                var allocation = new LeaveAllocationVM
                {
                    DateCreated = DateTime.Now,
                    EmployeeId = emp.Id,
                    LeaveTypeId = id,
                    NumberOfDays = leavetype.DefaultDays,
                    Period = DateTime.Now.Year
                };
                var leaveallocation = _mapper.Map<LeaveAllocation>(allocation);
                //await _leaveallocationrepo.Create(leaveallocation);
                await _unitOfWork.LeaveAllocations.Create(leaveallocation);
                await _unitOfWork.Save(); 
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task< ActionResult> ListEmployees()
        {
            var employees = await _userManager.GetUsersInRoleAsync("Employee");
            var model = _mapper.Map<List<EmployeeVM>>(employees);
            return View(model); 
        }

        public async Task<ActionResult> Details(string id)
        {
            
            // following is pretty much same as above, but now in one line 
            var employee =  _mapper.Map<EmployeeVM>(await _userManager.FindByIdAsync(id));
            var period = DateTime.Now.Year;
            //var allocations =  _mapper.Map<List<LeaveAllocationVM>>(await _leaveallocationrepo.GetLeaveAllocationsByEmployee(id));

            var records = await _unitOfWork.LeaveAllocations.FindAll(
                                expression: q => q.EmployeeId == id && q.Period == period,
                                includes: new List<string> { "LeaveType"}) ;

            var allocations = _mapper.Map<List<LeaveAllocationVM>>(records);

            var model = new ViewAllocationsVM
            {
                Employee = employee,
                leaveAllocations = allocations 
            };
            return View(model); 
        }

        public async Task< ActionResult> Edit(int id) {

            // var leaveallocation = await _leaveallocationrepo.FindById(id);
            var leaveallocation = await _unitOfWork.LeaveAllocations.Find(q => q.Id == id,
                                        includes: new List<string> { "Employee", "LeaveType" }); 
            var model = _mapper.Map<EditLeaveAllocationVM>(leaveallocation); 
            return View(model); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<ActionResult> Edit(EditLeaveAllocationVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model); 
                }
                // var record = await _leaveallocationrepo.FindById(model.Id);
                var record = await _unitOfWork.LeaveAllocations.Find(q => q.Id == model.Id); 
                record.NumberOfDays = model.NumberOfDays;
                // var isSuccess = await _leaveallocationrepo.Update(record);
                _unitOfWork.LeaveAllocations.Update(record);
                await _unitOfWork.Save(); 
                //if (!isSuccess)
                //{
                //    ModelState.AddModelError("", "Error while saving...");
                //    return View(model); 
                //}

                return RedirectToAction(nameof(Details), new {id = model.EmployeeId }); 
            }
            catch 
            {
                return View(model);
            }

            
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing); 
        }

    }
}

Views/LeaveAllocation/Details.cshtml
@model leave_management.Models.ViewAllocationsVM 

@{
    ViewData["Title"] = "Details";
}


<h2>Details for @Model.Employee.Firstname @Model.Employee.Lastname</h2>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Firstname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Firstname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Lastname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Lastname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Username)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Username)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Email)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.PhoneNumber)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.TaxId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.TaxId)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.DateJoined)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.DateJoined)
        </dd>

    </dl>

</div>


<hr />

<h2>Leave Allocations</h2>

<div class="card" >

    <ul class="list-group list-group-flush">
        @foreach (var item in Model.leaveAllocations)

           
        {
            <li class="list-group-item">
                <h6>@item.LeaveType.Name
                <span class="badge badge-secondary" > @item.NumberOfDays </span>
                <a asp-action="Edit"  asp-route-id="@item.Id" class="btn btn-outline-warning float-right">
                   <i class="fa fa-pencil"></i> Edit
                </a>
                </h6>
            </li>
        }

    </ul>
</div>
<br />
<div>
    <a class="btn btn-outline-secondary btn-block" asp-action="Index">Back to List</a>
    
</div>

Views/LeaveAllocation/Edit.cshtml
@model leave_management.Models.EditLeaveAllocationVM

@{
    ViewData["Title"] = "Edit"; 
}

<h2>Editing @Model.LeaveType.Name Allocation for @Model.Employee.Firstname @Model.Employee.Lastname </h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="EmployeeId" />
            <div class="form-group">
                <label asp-for="NumberOfDays" class="control-label"></label>
                <input asp-for="NumberOfDays" class="form-control" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-success btn-block" />
            </div>

        </form>
    </div>

</div>

<div>
    <a class="btn btn-outline-secondary btn-block" asp-action="Details" asp-route-id="@Model.EmployeeId">Back to Details</a>
</div>

Views/LeaveAllocation/Index.cshtml
@model leave_management.Models.CreateLeaveAllocationVM

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<table id="tblData" class="table" >
    <thead>
        <tr>

            <th>
                Leave Types
            </th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LeaveTypes)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @*@Html.ActionLink("Allocate To Employees", "SetLeave", new {  id=item.Id  } , new { @class = "btn btn-success"})*@
                    <a class="btn btn-outline-success" asp-action="SetLeave" asp-route-id="@item.Id">
                        <i class="fas fa-user-edit"></i> Allocate To Employees
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/LeaveAllocation/ListEmployees.cshtml
@model IEnumerable<leave_management.Models.EmployeeVM>


@{
    ViewData["Title"] = "ListEmployees";
}

<h1>List Employees</h1>

<table id="tblData" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Firstname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lastname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
             
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
           <tr>
            <td> @Html.DisplayFor(modelItem => item.Firstname)</td>

            <td>@Html.DisplayFor(modelItem => item.Lastname) </td>

            <td>@Html.DisplayFor(modelItem => item.Email) </td>

            <td>

                <a class="btn btn-outline-success" asp-controller="LeaveAllocation" asp-action="Details" asp-route-id="@item.Id" >
                <i class="fa fa-search"></i> Details
                </a>


               @*@Html.ActionLink("Details", "Details", new { id=item}, new {})*@

            </td>

           </tr>
        }


    </tbody>

</table>

@section Scripts{
    <script></script>

}